receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

exporters:
  tempo:
    endpoint: "tempo:3420"
  loki:
    endpoint: "http://loki:3410/loki/api/v1/push"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [tempo]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki]