auth_enabled: false

server:
  http_listen_port: 3410
  graceful_shutdown_timeout: 5s

#distributor:
#  ring:
#    kvstore:
#      store: memberlist

compactor:
  working_directory: /loki/compactor

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_target_size: 1048576
  lifecycler:
    join_after: 15s
    ring:
      replication_factor: 1
#      kvstore:
#        store: memberlist

common:
  ring:
    kvstore:
      store: memberlist


memberlist:
  join_members: []
  bind_port: 7946

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb/index
    cache_location: /loki/tsdb/cache
  filesystem:
    directory: /loki/tsdb/chunks

limits_config:
  max_line_size: 1024
  max_streams_per_user: 1000
  retention_period: 336h # 2 weeks

