receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch: {}

exporters:
  otlp:
    endpoint: "tempo:3421"
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: "http://loki:3410/otlp"
    tls:
      insecure: true
#  prometheusremotewrite:
#    endpoint: "http://prometheus:3430/v1/api/remote_write"

extensions:
  health_check:
  zpages:

service:
  extensions: [ health_check, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp/logs ]
#    metrics:
#      receivers: [ otlp ]
#      processors: [ batch ]
#      exporters: [ prometheusremotewrite ]