receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  tempo:
    endpoint: "tempo:3420"
  loki:
    endpoint: "http://loki:3410/loki/api/v1/push"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [tempo]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki]