[tool.poetry]
name = "multiagent-rag-system"
version = "0.1.0"
description = "A multiagent system to aid in learning programming languages and other tech"
authors = ["Jaka Krajnc <444.ous@gmail.com>"]
readme = "README.md"
packages = [
    { include = "server" },
    { include = "statemachine" },
    { include = "tools" },
]

[tool.poetry.dependencies]
python = "^3.12"
black = "^24.8.0"

[tool.isort]
profile = "black"

[tool.poetry.group.server.dependencies]
pytest = "^8.3.2"
fastapi = "^0.111.1"
websockets = "^13.0"
sqlmodel = "^0.0.22"
psycopg = "^3.2.1"

[tool.poetry.group.statemachine.dependencies]
langgraph = "^0.2.15"
langchain = "^0.2.12"
langchain-openai = "^0.1.20"
chromadb = "^0.5.5"
langchain-community = "^0.2.11"
langchain-chroma = "^0.1.2"
langgraph-checkpoint-postgres = "^1.0.5"
psycopg = "^3.2.1"
psycopg-pool = "^3.2.2"

[tool.poetry.group.tools.dependencies]
beautifulsoup4 = "^4.12.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
